#!/bin/bash
DAYS=20

if [ $1 ] 
then
    DAYS=$1
fi
echo "Doing $DAYS of data."

./tickfetch.rb -v -D $DAYS @ES#  @BP# @ED# @JE# @ME# 
./tickfetch.rb -v -D $DAYS @NQ# @ND# 

./tickfetch.rb -v -D $DAYS @SP# @ME# GOX.XO GVX.XO VXSLV.XO TNX.XO FVX.XO 

./tickfetch.rb -v -D $DAYS CSCO FB GOOG VRTX MRK GIS ZNGA BAC GM F C MSFT AAPL NOC
./tickfetch.rb -v -D $DAYS DI6A.Z DI6D.Z DI6T.Z DI6U.Z 
./tickfetch.rb -v -D $DAYS DJI2MN.X 
./tickfetch.rb -v -D $DAYS II6A.Z II6D.Z IINA.Z IIND.Z 

./tickfetch.rb -v -D $DAYS IINT.Z IINU.Z IR6T.Z 
./tickfetch.rb -v -D $DAYS JI6T.Z JT6T.Z JV6T.Z 
./tickfetch.rb -v -D $DAYS OC2T.Z OP2T.Z PRSC.Z PRSP.Z RI6T.Z 
./tickfetch.rb -v -D $DAYS SPY SPX.XO CYX.XO 
./tickfetch.rb -v -D $DAYS TI6A.Z TI6D.Z TICK.Z TRIN.Z 
./tickfetch.rb -v -D $DAYS VC2T.Z VI6A.Z VI6D.Z VI6U.Z VINA.Z VIND.Z 
./tickfetch.rb -v -D $DAYS VIX.XO VP2T.Z XAU.X 

# ETFs 
./tickfetch.rb -v -D $DAYS AGG MBB WPS DVY IXUS IVV EFA LQD

